[semver:minor] Add support for toggling tests with flags
myhelix/golang-orb pull request #51
Opened 2023-05-16 20:51 UTC by nick-armstrong-helix

## Background
The current `go-mod-ginkgo-v2` test orb can run two types of ginkgo tests, unit and acceptance. Furthermore extending the `go-mod-ginkgo-v2` job to support new test types is difficult due the method in which it identifies tests as unit vs. acceptance.

In order to support a more diverse range of test types I would like to propose the following job to detect tests using ginkgo's flag filtering system.

2023-06-06 21:49 UTC, zubinmadon reviewed
Nit: perhaps replace "flags" with "labels" or "label-filters" in the filenames, descpriptions, comments etc, to make it more clear how it differs from existing ginkgo jobs.

2023-10-12 23:49 UTC, nick-armstrong-helix commented
⚠️ auto-merge enabled ⚠️

2023-10-13 17:16 UTC, JackyLiHelix requested changes
Looks good overall. One minor improvement.

2023-10-13 17:16 UTC, JackyLiHelix commented on src/jobs/go-mod-ginkgo-v2-labels.yml
> +    default: ""
Same applies here.

2023-10-13 17:25 UTC, nick-armstrong-helix commented on src/commands/ginkgo-v2-labels.yml
> +    default: ""
Nice catch! Thank you!

2023-10-13 17:38 UTC, JackyLiHelix approved these changes

2023-10-13 20:47 UTC, merged