Add persist_to_workspace to go-mod-ginkgo-v2
myhelix/golang-orb pull request #56
Opened 2023-11-08 00:22 UTC by igwolff

Store test results to workspace to make them available to downstream jobs.

2023-11-08 00:25 UTC, ZuhaibSiddiqueHelix requested changes
Need to add root per documentation here https://circleci.com/docs/configuration-reference/#persisttoworkspace

2023-11-08 00:25 UTC, ZuhaibSiddiqueHelix commented on src/jobs/go-mod-ginkgo-v2.yml
> +  - persist_to_workspace:
docs says yes https://circleci.com/docs/configuration-reference/#persisttoworkspace

2023-11-09 18:33 UTC, JackyLiHelix approved these changes

2023-11-16 23:28 UTC, ZuhaibSiddiqueHelix approved these changes

2023-11-17 03:01 UTC, merged